package dml.qipairoomcard.repository;

import dml.largescaletaskmanagement.entity.CompleteSegmentIfTimeout;
import dml.largescaletaskmanagement.repository.SegmentProcessingTimeoutHandlingStrategyRepository;

public interface ClearRoomTaskSegmentTimeoutStrategyRepository extends SegmentProcessingTimeoutHandlingStrategyRepository<CompleteSegmentIfTimeout> {
}
